name: Publish Neuron Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: srid
      - uses: actions/checkout@v2
        with:
          repository: srid/neuron
          ref: v1
          path: neuron
      - run: nix-env -if .
        working-directory: neuron
      - run: rm -rf neuron
      - uses: actions/checkout@v2
      - name: Build neuron site
        run: neuron -d . rib
      - name: Netlify deploy
        run: |
          yarn global add netlify-cli
          "$(yarn global bin)/netlify" deploy --prod --dir=.neuron/output
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
